image: python:3.10.13

stages:
  - semgrep
  - test
  - publish

include:
  - project: 'meshcapade/cicd'
    ref: 0.0.20
    file:
      - 'semgrep.gitlab-ci.yml'

default:
  before_script: 
    - pip install --no-cache-dir poetry==1.7.1
    - poetry config --local repositories.gitlab https://gitlab.com/api/v4/projects/53021447/packages/pypi
    - poetry config --local virtualenvs.in-project true
    - ls -R

run-tests:
  stage: test
  script:
    - poetry install
    - poetry run pytest -v
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG

publish-private:
  stage: publish
  script:
    - poetry publish --build --no-interaction --no-ansi --username=gitlab-ci-token --password=${CI_JOB_TOKEN} --repository=gitlab
  rules:
    - if: $CI_COMMIT_TAG
