image: python:3.10.13

stages:
  - test
  - publish

default:
  before_script: 
    - pip install --no-cache-dir poetry==1.7.1
    - ls --recursive

run-tests:
  stage: test
  script:
    - poetry install
    - poetry run pytest -v
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

publish-private:
  stage: publish
  script:
    - poetry publish --build --no-interaction --no-ansi --username=gitlab-ci-token --password=${CI_JOB_TOKEN} --repository=gitlab
  rules:
    - if: $CI_COMMIT_TAG
